/**
 * 内置 DOCX Skill — 隐式注入，不展示在 Available Skills 列表中
 * 基于 Anthropic docx skill 适配，针对 Note Agent 环境优化
 */

/**
 * 检测是否需要注入 docx skill
 */
export function shouldInjectDocxSkill(
  userInput: string,
  openFiles?: string[],
): boolean {
  const docxKeywords = [
    '.docx', 'docx', 'word document', 'word 文件', 'word file',
    '.doc', 'doc 文件',
    'microsoft word',
    'create a document', '生成文档', '创建文档',
    'letter', 'memo', 'report', 'template',
    'table of contents', '页眉', '页脚', '目录',
    'track changes', '修订', '批注', 'comment',
  ]

  const lowerInput = userInput.toLowerCase()
  if (docxKeywords.some((kw) => lowerInput.includes(kw.toLowerCase()))) {
    return true
  }

  if (openFiles) {
    for (const f of openFiles) {
      const lower = f.toLowerCase()
      if (lower.endsWith('.docx') || lower.endsWith('.doc')) {
        return true
      }
    }
  }

  return false
}

const BQ = '`'.repeat(3)

/**
 * DOCX Skill 精简摘要 — 上下文紧张时使用
 */
export const DOCX_SKILL_SUMMARY = [
  '## DOCX Guidelines (Summary)',
  '- readFile on .docx extracts text automatically.',
  '- Edit existing docs: use the dedicated Word tools (replaceWordParagraph, addWordParagraph, deleteWordParagraph, modifyWordFormat). These preserve formatting and do NOT require generating temporary scripts.',
  '- ONLY fall back to XML editing when the Word tools cannot handle the specific requirement.',
  '- Create new docs: use `docx` npm package in `.note_agent/temp/` (see full guidelines).',
  '- ALL intermediate files (scripts, node_modules, unpacked) MUST stay in `.note_agent/temp/`.',
].join('\n')

/**
 * DOCX Skill 内容 — 适配 Note Agent 环境
 * 移除了 Python 脚本引用，替换为 shell/Node.js 方式
 */
export const DOCX_SKILL_CONTENT = [
  '## DOCX Document Guidelines',
  '',
  'A .docx file is a ZIP archive containing XML files. Use the following approaches depending on the task.',
  '',
  '### Reading Content',
  'Use the **readFile** tool on .docx files — it automatically extracts text content. For raw XML access, unpack the docx first (see Editing below).',
  '',
  '### Creating New Documents',
  '',
  'Generate .docx files with the "docx" npm package, then execute the script via **executeCommand**.',
  'ALL intermediate work MUST happen inside `.note_agent/temp/` — do NOT pollute the workspace root.',
  '',
  '`docx` is pre-installed. Use it directly without npm install.',
  '',
  '**Basic script pattern (save to .note_agent/temp/create-docx.js):**',
  BQ + 'javascript',
  'const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, ImageRun,',
  '        Header, Footer, AlignmentType, PageOrientation, LevelFormat, ExternalHyperlink,',
  '        InternalHyperlink, Bookmark, FootnoteReferenceRun, PositionalTab,',
  '        PositionalTabAlignment, PositionalTabRelativeTo, PositionalTabLeader,',
  '        TabStopType, TabStopPosition, Column, SectionType,',
  '        TableOfContents, HeadingLevel, BorderStyle, WidthType, ShadingType,',
  '        VerticalAlign, PageNumber, PageBreak } = require("docx");',
  'const fs = require("fs");',
  '',
  'const doc = new Document({ sections: [{ children: [/* content */] }] });',
  'Packer.toBuffer(doc).then(buffer => fs.writeFileSync("../../output.docx", buffer));',
  BQ,
  '',
  '**Execute:**',
  BQ + 'bash',
  'cd .note_agent/temp && node create-docx.js',
  BQ,
  '',
  '### Page Size (CRITICAL)',
  '',
  'docx-js defaults to A4. Always set page size explicitly.',
  '',
  BQ + 'javascript',
  'sections: [{',
  '  properties: {',
  '    page: {',
  '      size: {',
  '        width: 12240,   // 8.5 inches in DXA (1440 DXA = 1 inch)',
  '        height: 15840   // 11 inches in DXA',
  '      },',
  '      margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }',
  '    }',
  '  },',
  '  children: [/* content */]',
  '}]',
  BQ,
  '',
  '**Landscape:** Pass portrait dimensions, set orientation. docx-js swaps them internally.',
  BQ + 'javascript',
  'size: { width: 12240, height: 15840, orientation: PageOrientation.LANDSCAPE }',
  BQ,
  '',
  '### Styles (Override Built-in Headings)',
  '',
  'Use Arial as default font. Keep titles black.',
  '',
  BQ + 'javascript',
  'const doc = new Document({',
  '  styles: {',
  '    default: { document: { run: { font: "Arial", size: 24 } } }, // 12pt',
  '    paragraphStyles: [',
  '      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,',
  '        run: { size: 32, bold: true, font: "Arial" },',
  '        paragraph: { spacing: { before: 240, after: 240 }, outlineLevel: 0 } },',
  '      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,',
  '        run: { size: 28, bold: true, font: "Arial" },',
  '        paragraph: { spacing: { before: 180, after: 180 }, outlineLevel: 1 } },',
  '    ]',
  '  },',
  '  sections: [{',
  '    children: [',
  '      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("Title")] }),',
  '    ]',
  '  }]',
  '});',
  BQ,
  '',
  '### Lists (NEVER use unicode bullets)',
  '',
  BQ + 'javascript',
  '// Wrong:',
  'new Paragraph({ children: [new TextRun("• Item")] })',
  '',
  '// Correct:',
  'const doc = new Document({',
  '  numbering: {',
  '    config: [',
  '      { reference: "bullets",',
  '        levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,',
  '          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },',
  '      { reference: "numbers",',
  '        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,',
  '          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },',
  '    ]',
  '  },',
  '  sections: [{',
  '    children: [',
  '      new Paragraph({ numbering: { reference: "bullets", level: 0 },',
  '        children: [new TextRun("Bullet item")] }),',
  '      new Paragraph({ numbering: { reference: "numbers", level: 0 },',
  '        children: [new TextRun("Numbered item")] }),',
  '    ]',
  '  }]',
  '});',
  BQ,
  '',
  '### Tables',
  '',
  'CRITICAL: Tables need dual widths — set both "columnWidths" on the table AND "width" on each cell. Always use "WidthType.DXA" (percentages break in Google Docs).',
  '',
  BQ + 'javascript',
  'const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };',
  'const borders = { top: border, bottom: border, left: border, right: border };',
  '',
  'new Table({',
  '  width: { size: 9360, type: WidthType.DXA }, // US Letter with 1" margins',
  '  columnWidths: [4680, 4680],',
  '  rows: [',
  '    new TableRow({',
  '      children: [',
  '        new TableCell({',
  '          borders,',
  '          width: { size: 4680, type: WidthType.DXA },',
  '          shading: { fill: "D5E8F0", type: ShadingType.CLEAR }, // CLEAR not SOLID',
  '          margins: { top: 80, bottom: 80, left: 120, right: 120 },',
  '          children: [new Paragraph({ children: [new TextRun("Cell")] })]',
  '        })',
  '      ]',
  '    })',
  '  ]',
  '})',
  BQ,
  '',
  '- Table width must equal sum of columnWidths',
  '- Cell width must match corresponding columnWidth',
  '- Cell margins are internal padding (reduce content area, not add to width)',
  '',
  '### Images',
  '',
  BQ + 'javascript',
  'new Paragraph({',
  '  children: [new ImageRun({',
  '    type: "png", // Required: png, jpg, jpeg, gif, bmp, svg',
  '    data: fs.readFileSync("image.png"),',
  '    transformation: { width: 200, height: 150 },',
  '    altText: { title: "Title", description: "Desc", name: "Name" }',
  '  })]',
  '})',
  BQ,
  '',
  '### Page Breaks',
  '',
  BQ + 'javascript',
  'new Paragraph({ children: [new PageBreak()] })',
  '// Or: new Paragraph({ pageBreakBefore: true, children: [new TextRun("New page")] })',
  BQ,
  '',
  '### Hyperlinks',
  '',
  BQ + 'javascript',
  '// External',
  'new Paragraph({',
  '  children: [new ExternalHyperlink({',
  '    children: [new TextRun({ text: "Click here", style: "Hyperlink" })],',
  '    link: "https://example.com",',
  '  })]',
  '})',
  '',
  '// Internal bookmark',
  'new Paragraph({ heading: HeadingLevel.HEADING_1, children: [',
  '  new Bookmark({ id: "chapter1", children: [new TextRun("Chapter 1")] }),',
  '])})',
  'new Paragraph({ children: [new InternalHyperlink({',
  '  children: [new TextRun({ text: "See Chapter 1", style: "Hyperlink" })],',
  '  anchor: "chapter1",',
  '})] })',
  BQ,
  '',
  '### Headers/Footers',
  '',
  BQ + 'javascript',
  'sections: [{',
  '  headers: {',
  '    default: new Header({ children: [new Paragraph({ children: [new TextRun("Header")] })] })',
  '  },',
  '  footers: {',
  '    default: new Footer({ children: [new Paragraph({',
  '      children: [new TextRun("Page "), new TextRun({ children: [PageNumber.CURRENT] })]',
  '    })] })',
  '  },',
  '  children: [/* content */]',
  '}]',
  BQ,
  '',
  '### Table of Contents',
  '',
  BQ + 'javascript',
  'new TableOfContents("Table of Contents", { hyperlink: true, headingStyleRange: "1-3" })',
  BQ,
  'CRITICAL: Headings must use HeadingLevel ONLY — no custom styles on heading paragraphs.',
  '',
  '### Critical Rules for docx-js',
  '',
  '- Set page size explicitly — defaults to A4; use 12240 x 15840 DXA for US Letter',
  '- Landscape: pass portrait dimensions — docx-js swaps width/height internally',
  '- Never use backslash-n — use separate Paragraph elements',
  '- Never use unicode bullets — use LevelFormat.BULLET with numbering config',
  '- PageBreak must be in Paragraph — standalone creates invalid XML',
  '- ImageRun requires "type" — always specify png/jpg/etc',
  '- Always set table "width" with DXA — never PERCENTAGE',
  '- Tables need dual widths — columnWidths array AND cell width',
  '- Use ShadingType.CLEAR — never SOLID for table shading',
  '- Never use tables as dividers — use paragraph borders instead',
  '- TOC requires HeadingLevel only — no custom styles',
  '- Override built-in styles — use exact IDs: "Heading1", "Heading2"',
  '- Include outlineLevel — required for TOC (0 for H1, 1 for H2)',
  '',
  '---',
  '',
  '### Editing Existing Documents',
  '',
  'Three steps: Unpack → Edit XML → Repack',
  '',
  '#### Step 1: Unpack',
  '',
  BQ + 'bash',
  'mkdir -p .note_agent/temp/unpacked && unzip document.docx -d .note_agent/temp/unpacked/',
  BQ,
  '',
  'The main content is in ".note_agent/temp/unpacked/word/document.xml".',
  '',
  '#### Step 2: Edit XML',
  '',
  'Use **editFile** to modify XML in ".note_agent/temp/unpacked/word/". Use **writeFile** for new files.',
  '',
  'Use "Claude" as the author for tracked changes and comments, unless the user requests otherwise.',
  '',
  'CRITICAL: Use XML entities for smart quotes in new content:',
  '| Entity | Character |',
  '|--------|-----------|',
  '| &#x2018; | \' (left single) |',
  '| &#x2019; | \' (right single / apostrophe) |',
  '| &#x201C; | " (left double) |',
  '| &#x201D; | " (right double) |',
  '',
  'Example:',
  BQ + 'xml',
  '<w:t>Here&#x2019;s a quote: &#x201C;Hello&#x201D;</w:t>',
  BQ,
  '',
  '#### Step 3: Repack',
  '',
  BQ + 'bash',
  'cd .note_agent/temp/unpacked && zip -r ../../output.docx .',
  BQ,
  '',
  'Auto-repair notes: If Word reports corruption after repacking, common fixes:',
  '- Ensure "durableId" values are < 0x7FFFFFFF',
  '- Add "xml:space=\\"preserve\\"" to <w:t> elements with leading/trailing whitespace',
  '- Ensure all referenced images exist in word/media/ and have relationships in word/_rels/document.xml.rels',
  '',
  '---',
  '',
  '### Converting Formats',
  '',
  'DOC to DOCX:',
  BQ + 'bash',
  'soffice --headless --convert-to docx document.doc',
  BQ,
  '',
  'DOCX to PDF:',
  BQ + 'bash',
  'soffice --headless --convert-to pdf document.docx',
  BQ,
  '',
  'DOCX to images (via PDF):',
  BQ + 'bash',
  'soffice --headless --convert-to pdf document.docx',
  'pdftoppm -jpeg -r 150 document.pdf page',
  BQ,
  '',
  '---',
  '',
  '### XML Reference for Editing',
  '',
  '#### Tracked Changes',
  '',
  'Insertion:',
  BQ + 'xml',
  '<w:ins w:id="1" w:author="Claude" w:date="2025-01-01T00:00:00Z">',
  '  <w:r><w:t>inserted text</w:t></w:r>',
  '</w:ins>',
  BQ,
  '',
  'Deletion:',
  BQ + 'xml',
  '<w:del w:id="2" w:author="Claude" w:date="2025-01-01T00:00:00Z">',
  '  <w:r><w:delText>deleted text</w:delText></w:r>',
  '</w:del>',
  BQ,
  '',
  'Inside <w:del>: Use <w:delText> instead of <w:t>.',
  '',
  'Minimal edits — only mark what changes. Example changing "30 days" to "60 days":',
  BQ + 'xml',
  '<w:r><w:t>The term is </w:t></w:r>',
  '<w:del w:id="1" w:author="Claude" w:date="...">',
  '  <w:r><w:delText>30</w:delText></w:r>',
  '</w:del>',
  '<w:ins w:id="2" w:author="Claude" w:date="...">',
  '  <w:r><w:t>60</w:t></w:r>',
  '</w:ins>',
  '<w:r><w:t> days.</w:t></w:r>',
  BQ,
  '',
  'Deleting entire paragraphs: Add <w:del/> inside <w:pPr><w:rPr>:',
  BQ + 'xml',
  '<w:p>',
  '  <w:pPr>',
  '    <w:rPr>',
  '      <w:del w:id="1" w:author="Claude" w:date="2025-01-01T00:00:00Z"/>',
  '    </w:rPr>',
  '  </w:pPr>',
  '  <w:del w:id="2" w:author="Claude" w:date="2025-01-01T00:00:00Z">',
  '    <w:r><w:delText>Entire paragraph...</w:delText></w:r>',
  '  </w:del>',
  '</w:p>',
  BQ,
  '',
  '#### Schema Compliance',
  '',
  '- Element order in <w:pPr>: <w:pStyle>, <w:numPr>, <w:spacing>, <w:ind>, <w:jc>, <w:rPr> last',
  '- Whitespace: Add xml:space="preserve" to <w:t> with leading/trailing spaces',
  '- RSIDs: Must be 8-digit hex (e.g., 00AB1234)',
  '',
  '---',
  '',
  '### Editing Existing Word Documents',
  '',
  'When the user asks you to modify content in an existing .docx file, you MUST use the dedicated Word tools.',
  'These tools preserve all original formatting (styles, fonts, spacing, etc.) and do NOT require generating temporary scripts.',
  '',
  '**Available tools (use these FIRST before resorting to XML editing):**',
  '',
  '- **replaceWordParagraph** — Replace the text of a specific paragraph.',
  '- **addWordParagraph** — Insert a new paragraph before a specific paragraph (inherits formatting).',
  '- **deleteWordParagraph** — Delete a specific paragraph.',
  '- **modifyWordFormat** — Modify formatting (heading level, alignment, font size, bold, italic, color, indentation) for a specific paragraph or globally.',
  '',
  '**CRITICAL: Do NOT generate temporary JavaScript/Node.js scripts to edit .docx files.**',
  'The Word tools above are the correct, atomic way to modify documents. Only fall back to XML editing for operations that these tools cannot perform.',
  '',
  'Do NOT simply return the modified text in your response. Always call the appropriate Word tool to apply changes.',
  '',
  'Steps when the user quotes a paragraph and asks for modifications:',
  '1. Identify the paragraph number from the user\'s quote (paragraph numbers start from 1)',
  '2. Determine which Word tool is appropriate (replace, add, delete, or modify format)',
  '3. Call the tool with the file path, paragraph number (1-based), and required parameters',
  '4. After the operation succeeds, call **done** to end the session',
  '5. Confirm to the user that the change has been applied',
].join('\n')
